### ISSUE TITLE
Using outdated version of `gatsby-theme-blog-core`

### ISSUE THREAD

**Issue by crhayes** [gatsbyjs/gatsby-starter-blog-theme-core#6]
Has a dependency on V1 rather than V2 of `gatsby-theme-blog-core`. Should probably be updated to `"gatsby-theme-blog-core": "^2.0.2"`

https://github.com/gatsbyjs/gatsby-starter-blog-theme-core/blob/master/package.json#L15

@LekoArts Just posting this as a reminder from the following discussion:
https://github.com/gatsbyjs/gatsby/discussions/27717

**Comment by LekoArts** [comment]
Will be addressed here: https://github.com/gatsbyjs/gatsby/pull/27722
